name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear
        
      - name: Restore dependencies
        working-directory: EMGMAND
        run: |
          dotnet restore
          dotnet add package Microsoft.TestPlatform.TestHost --version 17.11.1
          
      - name: Build
        working-directory: EMGMAND
        run: dotnet build

      - name: Test
        working-directory: EMGMAND
        run: dotnet test